export const TOGGLE_ITEM_IN_CART='TOGGLE_ITEM_IN_CART';
export const CLEAR_CART='CLEAR_CART';
export const REMOVE_ITEM='REMOVE_ITEM';
export const ADD_ITEM_QTY='ADD_ITEM_QTY';
export const DECREASE='DECREASE'
